encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("random", views.randompage, name="randompage"),
    path("new", views.newpage, name="new"),
    path("wiki/<str:entry>/edit", views.editpage, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
import random

from . import util
import markdown2

# This class defines the form required to edit an article and its respective styles

class ArticleForm(forms.Form):
    title = forms.CharField(label="Title" )
    content = forms.CharField(max_length = 20000, label = "Content", widget=forms.Textarea(attrs = {'cols': 'auto',
    'rows': '5',
    'placeholder': '# Title \n\nStart typing your article here!'}))

    title.widget.attrs.update({'class': 'titlebox', 'placeholder': 'Name your entry'})
    content.widget.attrs.update({'class': 'contentbox'})

# Returns a page with a list of all the entries and its lenght

def index(request):
    entries = util.list_entries()
    return render(request, "encyclopedia/index.html", {
        "entries": entries,
        "total_entries": len(entries),
    })

# Returns a page with the contents of an entry or an error page if it doesn't exist

def entry (request, entry):
    try:
        content = markdown2.markdown(util.get_entry(entry), extras=["tables", "fenced-code-blocks"])
        return render(request, "encyclopedia/entry.html", {"content": content, "entry": entry})
    except TypeError:
        return render (request, "encyclopedia/404.html", {"entry": entry.capitalize()})

# Returns a page with a list of all the entries that contains the get request as a substring
# If there is an exact match, redirects to that entry instead
# If there aren't any results then displays an error message

def search (request):
    # List with all the entries
    entries = util.list_entries()
    results = []
    input = request.GET['q']
 
    for entry in entries:
        # If there is an exact match between the input and the entry it redirects to it
        if input.lower() == entry.lower(): return redirect("wiki:entry", input)
        # If the input exists as a substring inside the entry the last gets appended to the results list
        elif input.lower() in entry.lower(): results.append(entry)
        # Otherwise check the next element
        else: continue

    if results == []: empty = 1
    else: empty = 0

    return render(request, "encyclopedia/search.html", {
        "entries": results,
        "empty": empty,
        "input": input,
    })

# Redirects to a random page in the entry list

def randompage (request):
    a = random.choice(util.list_entries())
    return redirect ("wiki:entry", a)

# If it receives a get request, displays the form for the creation of a new entry

# Then when receiving a post request, it creates a new markdown file with the contents filled by the user

def newpage (request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            entries = util.list_entries()
            for entry in entries:
                if form.cleaned_data["title"] == entry:
                    return render (request, "encyclopedia/new.html", {
                    "form": form,
                    "error": 'This article already exist!'})
            
            util.save_entry(form.cleaned_data["title"], form.cleaned_data["content"])
            return redirect("wiki:entry", form.cleaned_data["title"])
    return render (request, "encyclopedia/new.html", {
        "form": ArticleForm(),
        "error": '',
    })

# When receving a get request, displays a form similar to the one in the newpage view
# but it comes already filled with the contents of its corresponding markdown file

# Then when it receives a post request by the user it overwrites the entry with the data in the new request

# The user can't change the name of the file by design

def editpage (request, entry):
    if request.method == "POST":
        form = ArticleForm (request.POST)
        print(entry)
        if form.is_valid():
            util.save_entry(entry,form.cleaned_data["content"])
            return redirect("wiki:entry", entry)
        else:
            return render (request, "encyclopedia/new.html", {
            "form": form,
            "error": 'Invalid Form',
            "entry": entry
        })

    else:
        form = ArticleForm ({'title': entry, 'content': util.get_entry(entry)})
        print(entry)
        return render (request, "encyclopedia/edit.html", {
        "form": form,
        "error": '',
        "entry": entry,
        })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Editing: {{ entry }} | Encyclopedia
{% endblock %}

{% block body %}
    <a class="cornerlink" href="{% url 'wiki:entry' entry %}">Back</a>
    <h1>Edit Page</h1>
    <div><form action="{% url 'wiki:edit' entry %}" method="post">
        {% csrf_token %}
        <div>{{ form.title.label }}</div>
        <div><input type="text" name="title" value="{{ entry }}" class="titlebox" readonly="readonly" required="" id="id_title"></div>
        <div class="error">{{ error }}</div>
        <div>{{ form.content.label }}</div>
        <div>{{ form.content }}</div>
        <input type="submit" class="sbutton">
    </form></div>  
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry }} | Encyclopedia
{% endblock %}

{% block body %}
    <a class="cornerlink" href="{% url 'wiki:edit' entry %}">Edit</a>
    {{ content |safe}}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Index | Encyclopedia
{% endblock %}

{% block body %}
    <h1>Welcome to my website!</h1>
    <p>This was made as the Project 1 in the CS50’s Web Programming with Python and JavaScript course</p>
    <p>The project is (probably) finished by now!</p>
    <p>There are currently {{ total_entries }} entries</p>

    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="sidebar">
                    <h2>Wiki</h2>
                    <form action="{% url 'wiki:search' %}" method="get">
                        
                        <input class="search" type="text" name="q" placeholder="Search for an entry">
                        <input type="submit" value="Search" class="sbutton">
                    </form>
                    <div>
                        <a href="{% url 'wiki:index' %}">Home</a>
                    </div>
                    <div>
                        <a href="{% url 'wiki:new' %}">Create a New Page</a>
                    </div>
                    <div>
                        <a href="{% url 'wiki:randompage' %}">Random Page</a>
                    </div>
                    {% block nav %}
                    {% endblock %}
                </div>
                <div class="main col-md-9">
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a New Page | Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create a New Page</h1>
    <div>
        <form action="{% url 'wiki:new' %}" method="post">
            {% csrf_token %}
            <div>{{ form.title.label }}</div>
            <div>{{ form.title }}</div>
            <div class="error">{{ error }}</div>
            <div>{{ form.content.label }}</div>
            <div>{{ form.content }}</div>
            <input type="submit" class="sbutton">
        </form>
        
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ input }} - Search | Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results for {{ input }}</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}

        {% if empty %}
            <p>No results...</p>
        {% endif %}
    </ul>
{% endblock %}